import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [showMobileMenu, setShowMobileMenu] = useState(false);

  const experience = [
    {
      role: "React Js Developer",
      company_name: "InsuranceDekho",
      duration: "Mar 2024 - Sept 2024",
      role_summary:
        "Employee of Nuvento Systems, was hired for the client - InsuranceDekho.com to architect and lead the frontend development for their newly launched financial services vertical.",
      role_points: [
        "Designed and implemented the complete end-to-end transaction flow for both Credit Cards and Personal Loans, ensuring secure and efficient processing.",
        "Automated WhatsApp share link generation, resulting in a 27% increase in user engagement through the creation of a new public webpage.",
        "Introduced Redux for optimized state management, ensuring smooth and efficient data flow across the application.",
        "Led end-to-end project responsibilities, gaining valuable experience with Node.js, Express.js, and MongoDB.",
      ],
      skills: [
        { name: "React Js", level: "Expert" },
        { name: "Next.js", level: "Expert" },
        { name: "Redux", level: "Expert" },
        { name: "Javascript", level: "Expert" },
        { name: "Express.js", level: "Beginner" },
        { name: "Node.js", level: "Beginner" },
        { name: "MongoDB", level: "Beginner" },
      ],
    },

    {
      role: "Associate Software Developer",
      company_name: "Big Oh Tech",
      duration: "Oct 2022 - Mar 2024",
      role_summary:
        "Started my career with this startup, Got to work upon variuos dynamic projects, Worked in service projects, which requires dealing with client and working on the feedbacks, also contributed to the product of the organization - Microsite Builder",
      role_points: [
        "Improved the company's official website's performance, achieving a 40% increase in Lighthouse score.",
        "Developed a comprehensive resource architecture, including pages for video, news, blogs, and case studies, with server-side rendering and SEO-friendly detailed pages.",
        "Created various UI components, integrated with Redux and API integrations.",
        "Utilized Material-UI to develop a seamless user interface for components.",
        "Implemented React Hook Form for efficient form management and React Query for effective API state management.",
      ],
      skills: [
        { name: "React Js", level: "Expert" },
        { name: "Next.js", level: "Expert" },
        { name: "Redux", level: "Expert" },
        { name: "Javascript", level: "Expert" },
        { name: "HTML", level: "Intermediate" },
        { name: "CSS", level: "Intermediate" },
        { name: "React Query", level: "Intermediate" },
        { name: "Material Ui", level: "Intermediate" },
        { name: "React Hooks Forms", level: "Intermediate" },
        { name: "Jest Testing", level: "Intermediate" },
      ],
    },
  ];

  function toggleMenu(e) {
    e.stopPropagation();
    setShowMobileMenu((p) => !p);
  }

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Ashish Verma | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav id="desktop-nav" className={styles.desktop_nav}>
        <div className={styles.logo}>Ashish Verma</div>
        <div>
          <ul className={styles.nav_links}>
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#experience">Experience</a>
            </li>
            <li>
              <a href="#projects">Projects</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
      <nav id="hamburger-nav" className={styles.hamburger_nav}>
        <div className={styles.logo}>Ashish Verma</div>
        <div className={styles.hamburger_menu} onClick={toggleMenu}>
          {showMobileMenu ? (
            <div className={styles.cross_icon}>
              <b>X</b>
            </div>
          ) : (
            <div className={styles.hamburger_icon}>
              <span></span>
              <span></span>
              <span></span>
            </div>
          )}
          {showMobileMenu && (
            <div className={styles.menu_links}>
              <li>
                <a href="#about" onClick={toggleMenu}>
                  About
                </a>
              </li>
              <li>
                <a href="#experience" onClick={toggleMenu}>
                  Experience
                </a>
              </li>
              <li>
                <a href="#projects" onClick={toggleMenu}>
                  Projects
                </a>
              </li>
              <li>
                <a href="#contact" onClick={toggleMenu}>
                  Contact
                </a>
              </li>
            </div>
          )}
        </div>
      </nav>
      <section id="profile" className={`${styles.section} ${styles.profile}`}>
        <div className={styles.section__pic_container}>
          <img
            src="./assets/professional_ashish_passport.jpg"
            alt="John Doe profile picture"
          />
        </div>
        <div className={styles.section__text}>
          <p className={styles.section__text__p1}>Hello, I'm</p>
          <h1 className={styles.title}>Ashish Verma</h1>
          <p className={styles.section__text__p2}>React Js Developer</p>
          <div className={styles.btn_container}>
            <button
              className={`${styles.btn} ${styles.btn_color_2}`}
              onClick={() => window.open("./assets/Ashish_Verma_Resume.pdf")}
            >
              Download CV
            </button>
            <button
              className={`${styles.btn} ${styles.btn_color_1}`}
              onClick={() => (location.href = "./#contact")}
            >
              Contact Info
            </button>
          </div>
          <div id="socials-container" className={styles.socials_container}>
            <Link
              href="https://www.linkedin.com/in/ashishvermarch/"
              target="_blank"
            >
              <img
                src="./assets/linkedin.png"
                alt="My LinkedIn profile"
                className={styles.icon}
              />
            </Link>

            <Link href="https://github.com/ashishvermarch" target="_blank">
              <img
                src="./assets/github.png"
                alt="My Github profile"
                className={styles.icon}
              />
            </Link>
          </div>
        </div>
      </section>
      <section id="about" className={`${styles.section} ${styles.about}`}>
        <p className={styles.section__text__p1}>Get To Know More</p>
        <h1 className={styles.title}>About Me</h1>
        <div className={styles.section_container}>
          <div className={styles.section__pic_container}>
            <img
              src="./assets/dpwhatsapp.jpg"
              alt="Profile picture"
              className={styles.about_pic}
            />
          </div>
          <div className={styles.about_details_container}>
            <div className={styles.about_containers}>
              <div className={styles.details_container}>
                <img
                  src="./assets/experience.png"
                  alt="Experience icon"
                  className={styles.icon}
                />
                <h3>Experience</h3>
                <p>
                  2+ years <br />
                  Frontend Development
                </p>
              </div>
              <div className={styles.details_container}>
                <img
                  src="./assets/education.png"
                  alt="Education icon"
                  className={styles.icon}
                />
                <h3>Education</h3>
                <p>
                  10th & 12th CBSE
                  <br />
                  B.Tech CSE
                </p>
              </div>
            </div>
            <div className={styles.text_container}>
              <p>
                My name is Ashish Verma, and I’m a ReactJS Developer with two
                years of experience. Over the past two years, I have honed my
                skills in ReactJS, Next.js, JavaScript, Redux, HTML, and CSS.
                Crafting seamless user experiences is not just a job for me;
                it’s my passion. Currently, I am also learning Node.js and
                Express.js, and I have six months of hands-on experience with
                them.
              </p>
            </div>
          </div>
        </div>
        <img
          src="./assets/arrow.png"
          alt="Arrow icon"
          className={`${styles.icon} ${styles.arrow}`}
          onClick={() => (location.href = "./#experience")}
        />
      </section>
      <section
        id="experience"
        className={`${styles.section} ${styles.experience}`}
      >
        <p className={styles.section__text__p1}>Explore My</p>
        <h1 className={styles.title}>Experience</h1>
        <div className={styles.experience_details_container}>
          <div className={styles.about_containers}>
            {experience?.map((exp) => (
              <div className={styles.details_container}>
                <div className={styles.header}>
                  <h2 className={styles.position}>{exp.role}</h2>
                  <div className={styles.company_duration}>
                    <h3 className={styles.company_name}>{exp.company_name}</h3>
                    <p className={styles.duration}>{exp.duration}</p>
                  </div>
                </div>

                <div className={styles.summary_section}>
                  <h3 className={styles.summary_title}>Role Summary</h3>
                  <p className={styles.role_summary}>{exp.role_summary}</p>
                  <ul className={styles.additional_details}>
                    {exp.role_points?.map((p) => (
                      <li>{p}</li>
                    ))}
                  </ul>
                </div>

                <div className={styles.skills_section}>
                  <h3 className={styles.skills_title}>Skills</h3>
                  <div className={styles.article_container}>
                    <ol className={styles.article_container}>
                      {exp.skills.map((skill) => (
                        <li>
                          <h5>{skill.name}</h5>
                          <p>{skill.level}</p>
                        </li>
                      ))}
                    </ol>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
        <img
          src="./assets/arrow.png"
          alt="Arrow icon"
          className={`${styles.icon} ${styles.arrow}`}
          onClick={() => (location.href = "./#projects")}
        />
      </section>
      <section id="projects" className={`${styles.section} ${styles.projects}`}>
        <p className={styles.section__text__p1}>Browse My Recent</p>
        <h1 className={styles.title}>Projects</h1>
        <div className={styles.experience_details_container}>
          <div className={styles.about_containers}>
            <div
              className={`${styles.details_container} ${styles.color_container}`}
            >
              <div className={styles.article_container}>
                <img
                  src="./assets/builder.png"
                  alt="Project 1"
                  className={styles.project_img}
                />
              </div>
              <h2
                className={`${styles.experience_sub_title} ${styles.project_title}`}
              >
                Microsite Bulider
              </h2>
              <div className={styles.btn_container}>
                {/* <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onclick="location.href='https://github.com/'"
                >
                  Github
                </button> */}
                <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onClick={() =>
                    (location.href =
                      "https://stg.createwith.botshot.ai/admin/login")
                  }
                >
                  Live Demo
                </button>
              </div>
            </div>
            <div
              className={`${styles.details_container} ${styles.color_container}`}
            >
              <div className={styles.article_container}>
                <img
                  src="./assets/botshot.ai.png"
                  alt="Project 2"
                  className={styles.project_img}
                />
              </div>
              <h2
                className={`${styles.experience_sub_title} ${styles.project_title}`}
              >
                Botshot.ai
              </h2>
              <div className={styles.btn_container}>
                {/* <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onclick="location.href='https://github.com/'"
                >
                  Github
                </button> */}
                <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onClick={() => (location.href = "https://botshot.ai/")}
                >
                  Live Demo
                </button>
              </div>
            </div>
            <div
              className={`${styles.details_container} ${styles.color_container}`}
            >
              <div className={styles.article_container}>
                <img
                  src="./assets/task-management.png"
                  alt="Project 3"
                  className={styles.project_img}
                />
              </div>
              <h2
                className={`${styles.experience_sub_title} ${styles.project_title}`}
              >
                Task Management App
              </h2>
              <div className={styles.btn_container}>
                {/* <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onclick="location.href='https://github.com/'"
                >
                  Github
                </button> */}
                <button
                  className={`${styles.btn} ${styles.btn_color_2} ${styles.project_btn}`}
                  onClick={() =>
                    (location.href =
                      "https://ashish-task-management.vercel.app/")
                  }
                >
                  Live Demo
                </button>
              </div>
            </div>
          </div>
        </div>
        <img
          src="./assets/arrow.png"
          alt="Arrow icon"
          className={`${styles.icon} ${styles.arrow}`}
          onClick={() => (location.href = "./#contact")}
        />
      </section>
      <section id="contact" className={`${styles.section} ${styles.contact}`}>
        <p className={styles.section__text__p1}>Get in Touch</p>
        <h1 className={styles.title}>Contact Me</h1>
        <div className={styles.contact_info_upper_container}>
          <div className={styles.contact_info_container}>
            <img
              src="./assets/email.png"
              alt="Email icon"
              className={`${styles.icon} ${styles.contact_icon} ${styles.email_icon}`}
            />
            <p>
              <a href="mailto:ashishvermarch@gmail.com">
                ashishvermarch@gmail.com
              </a>
            </p>
          </div>
          <div className={styles.contact_info_container}>
            <img
              src="./assets/linkedin.png"
              alt="LinkedIn icon"
              className={`${styles.icon} ${styles.contact_icon}`}
            />
            <p>
              <a
                href="https://www.linkedin.com/in/ashishvermarch/"
                target="_blank"
              >
                LinkedIn
              </a>
            </p>
          </div>
        </div>
      </section>
      <footer>
        <nav>
          <div className={styles.nav_links_container}>
            <ul className={styles.nav_links}>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
                <a href="#experience">Experience</a>
              </li>
              <li>
                <a href="#projects">Projects</a>
              </li>
              <li>
                <a href="#contact">Contact</a>
              </li>
            </ul>
          </div>
        </nav>
        <p>Copyright &#169; 2024 Ashish Verma. All Rights Reserved.</p>
        <img
          src="./assets/arrow.png"
          alt="Arrow icon"
          className={`${styles.icon} ${styles.footer_arrow}`}
          onClick={() => (location.href = "./#profile")}
        />
      </footer>
    </div>
  );
}
